export const subRegions = [
  "Southern Europe",
  "Southeast Europe",
  "Northern Europe",
  "Central Europe",
  "Eastern Africa",
  "Western Africa",
  "Northern Africa",
  "Middle Africa",
  "South America",
  "North America",
  "Central America",
  "Caribbean",
  "Central Asia",
  "South-Eastern Asia",
  "Western Asia",
  "Eastern Asia",
  "Polynesia",
  "Melanesia",
  "Australia and New Zealand",
  "Micronesia",
];
